### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by sabond** [kimuraz/vue-interact#6]
Any ETA on documentation?

**Comment by kimuraz** [comment]
Sry @sabond this is a quite old repo and I didn't continue the development, I'll make sure to develop the documentation and change the project structured to a better one in the next few days.

**Comment by sabond** [comment]
Sounds good, thanks!

**Comment by kimuraz** [comment]
Pre-release v0.1.0 with new mixins and components
https://vue-interact.netlify.com/
