### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue-interact.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by vesper8** [kimuraz/vue-interact#68]
I'm trying to use this on a vue 3 project with vite 5 and getting this odd error

I've tried both `import VueInteract from 'vue-interact';` and `import { VueInteract } from 'vue-interact';`

And both statements are failing with the same error.. really confused why that's happening..

**Comment by kimuraz** [comment]
Sry, basically I'm not maintaining it anymore due to lack of time, but I've made some refactoring and released a v2, tested on a demo project, there are also some updates to the docs as well. I'd recommend to no even use the Plugin part since the composables would be enough in general.
